### ISSUE TITLE
搜尋之後，再次搜尋還是會出現同樣結果。（不知道是不是 bug)

### ISSUE THREAD

**Issue by clonn** [Cing-Jhih/lets_play#151]

**Comment by badbugwen** [comment]
請問您指的是"推薦遊戲"之後"再推薦"仍然出現同樣遊戲嗎？還是在左上放"找遊戲"輸入關鍵字，搜尋出符合關鍵字的遊戲結果重複呢？
如果是前者，應該是資料庫內遊戲資料不多，符合該年齡-情境的遊戲資料只有一筆所致。
如果是後者，希望您能截圖或敘述詳細操作過程，才能回答您的問題，謝謝！

**Comment by clonn** [comment]
```
請問您指的是"推薦遊戲"之後"再推薦"仍然出現同樣遊戲嗎？還是在左上放"找遊戲"輸入關鍵字，搜尋出符合關鍵字的遊戲結果重複呢？
```

這邊的部分是指前者，那應該就是剛好找的資料只有幾筆，導致不斷出現相同結果
